name: mcbroken-dashboard
services:
  - name: grafana
    github:
      repo: circa10a/digitalocean-hackathon
      branch: dev
    dockerfile_path: grafana/Dockerfile
    http_port: 3000
    health_check:
      http_path: /api/health
  - name: prometheus
    github:
      repo: circa10a/digitalocean-hackathon
      branch: dev
    dockerfile_path: prometheus/Dockerfile
    http_port: 9090
    health_check:
      http_path: /-/healthy
    routes:
    - Path: /prometheus
  - name: exporter
    github:
      repo: circa10a/digitalocean-hackathon
      branch: dev
    http_port: 8080
    health_check:
      http_path: /metrics
    routes:
    - Path: /mcbroken-metrics