---
github_repo: &github_repo
  github:
    repo: circa10a/digitalocean-hackathon
    branch: main

name: mcbroken-dashboard
services:
  - name: grafana
    << : *github_repo
    dockerfile_path: grafana/Dockerfile
    http_port: 3000
    health_check:
      http_path: /api/health
    envs:
    - key: GF_SERVER_ROOT_URL
      scope: RUN_TIME
      value: ${_self.PUBLIC_URL}
    routes:
      - Path: /grafana
  - name: prometheus
    << : *github_repo
    dockerfile_path: prometheus/Dockerfile
    http_port: 9090
    health_check:
      http_path: /-/healthy
  - name: exporter
    << : *github_repo
    http_port: 8080
    health_check:
      http_path: /metrics
    routes:
      - Path: /mcbroken
