---
global:
  scrape_interval:     120s
  evaluation_interval: 15s
scrape_configs:
  - job_name: mcbroken-exporter
    static_configs:
    - targets: ['exporter:8080']
  - job_name: digitalocean-exporter
    scheme: https
    static_configs:
    - targets: ['digitalocean-exporter-gm83a.ondigitalocean.app:443']
